from src.wikipls import *

a = Article("Pumped_Up_Kicks")
print(f"{a.details=}")
print(f"{a.id=}")
print(f"{a.title=}")
print(f"{a.key=}")
print(f"{a.content_model=}")
print(f"{a.license=}")
print(f"{a.latest=}")
print(f"{a.html_url=}")

p: Page = a.get_page()

print(f"\n{p.title=}")
print(f"{p.key=}")
print(f"{p.article_id=}")
print(f"{p.lang=}")
print(f"{p.content_model=}")
print(f"{p.license=}")
print(f"{p.revision_id=}")
# print(f"{p.html_url=}")
print(f"{p.date=}")
print(f"{p.views=}")
print(f"{p.html[:20]=}")
print(f"{p.summary[:20]=}")
print(f"{p.media=}")
print(f"{p.as_pdf[:20]=}")
print(f"{p.data=}")

r: Revision = p.get_revision()
print(f"\n{r.details=}")
print(f"{r.id=}")
print(f"{r.datetime=}")
print(f"{r.lang=}")
print(f"{r.user=}")
print(f"Page: {r.article_title=}, {r.article_key=}, {r.article_id=}")
print(f"{r.comment=}")
print(f"{r.delta=}")
print(f"{r.content_model=}")
print(f"{r.license=}")
print(f"{r.html_url=}")
print(f"{r.is_minor=}")
print(f"{r.size=}")

with open("test_pdf.pdf", 'wb') as f:
    f.write(p.as_pdf)
