from src.wikipls import *

a = Article("Pumped_Up_Kicks")
# a = Article("Ohio")
print(f"{a.details=}")
print(f"{a.id=}")
print(f"{a.title=}")
print(f"{a.key=}")
print(f"{a.content_model=}")
print(f"{a.license=}")
print(f"{a.latest=}")
print(f"{a.html_url=}")
print("-".rjust(30))

p: Page = a.get_page()

print(f"\n{p.from_article=}")
print(f"{p.article_id=}")
print(f"{p.revision_id=}")
print(f"{p.date=}")
print(f"{p.html[:20]=}")

print(f"{p.key=}")
print(f"{p.content_model=}")
print(f"{p.license=}")
print(f"{p.html_url=}")

print(f"{p.lang=}")

# print(f"\n{p.data_parsoid=}")
print(f"{p.lint=}")
# print(f"{p.segments=}")
print(f"{p.mobile_html[:50]=}")
print(f"{p.mobile_html_offline_resources=}\n\n\n")
print(f"{p.mobile_sections[:50]=}")
print(f"{p.mobile_sections_lead[:50]=}")
print(f"{p.mobile_sections_remaining[:50]=}")
print(f"{p.discussion['topics'][0]=}")
print(f"{p.related=}")
print(f"{p.raw_text[:50]=}")
print(f"{p.views=}")
print("p.summary={" + f"'html': {p.summary['html'][:50]}" + ", " + f"'text': {p.summary['text'][:50]}")
print(f"{p.media[0]=}")
print(f"{p.as_pdf[:20]=}")
print(f"{p.data=}")
print(f"{p.get_revision()=}")
print("-".rjust(30))


r: Revision = p.get_revision()
print(f"\n{r.details=}")
print(f"{r.id=}")
print(f"{r.datetime=}")
print(f"{r.lang=}")
print(f"{r.user=}")
print(f"Page: {r.article_title=}, {r.article_key=}, {r.article_id=}")
print(f"{r.comment=}")
print(f"{r.delta=}")
print(f"{r.content_model=}")
print(f"{r.license=}")
print(f"{r.html_url=}")
print(f"{r.is_minor=}")
print(f"{r.size=}")

with open("test_pdf.pdf", 'wb') as f:
    f.write(p.as_pdf)
